### ISSUE TITLE
breaks for switch statement

### ISSUE THREAD

**Issue by ajwells** [kuro68k/xmega_twi#1]
When I was trying to get my TWI interrupt lib working I had also tried yours as well. I did notice that there weren't breaks in between the outer most [switch statement](https://github.com/kuro68k/xmega_twi/blob/master/xmega_twi/twi.c#L272) in the ISR. I think there should at least be one [here](https://github.com/kuro68k/xmega_twi/blob/master/xmega_twi/twi.c#L301) and [here](https://github.com/kuro68k/xmega_twi/blob/master/xmega_twi/twi.c#L324). Not sure you care or not, but just thought I would let you know if you ever did want to use it. Thanks for the example btw.

**Comment by kuro68k** [comment]
Thanks, I implemented your changes: https://github.com/kuro68k/xmega_twi/commit/6d59c5d6297f063e8f59cca57ab5091a96f3b0cd

Glad it was of some help.
